site_name: Eric Seaman
nav: 
  - Home: index.md
  - Digital Media: Portfolio.md
  - Traditional Media: OCP.md
theme:
  name: material
  icon: 
    logo: simple/antdesign
  features: 
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      primary: blue
      accent: sea blue
repo_url: https://github.com/EGSeaman/EGSeaman.github.io
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg